### ISSUE TITLE
typo in your model

### ISSUE THREAD

**Issue by bchiu** [developer0hye/Simple-CenterNet#26]
https://github.com/developer0hye/Simple-CenterNet/blob/680584cf038194e6f5e58a7026ebd5d100bec582/models/centernet.py#L156

"position:" should be "position"

**Comment by developer0hye** [comment]
@bchiu Thanks for your contribution!

**Comment by ushio20** [comment]
why before I fix this bug I can also get the map however?Very confused.

**Comment by ushio20** [comment]
Why before I fix this bug I can also get the map however?It made me very confused.

**Comment by ushio20** [comment]
Yes,it should be a error because the field name doesn't match,however,it works...

**Comment by developer0hye** [comment]
@ushio20 
If the key doesn't  exist in dictionary, it is generated when the value is initialized. So, this bug didn't affect critical issue.

**Comment by ushio20** [comment]
> @ushio20
> If the key doesn't exist in dictionary, it is generated when the value is initialized. So, this bug didn't cause critical issue.

OK,I understand,thank you very much.
