### ISSUE TITLE
Loss repeated average.

### ISSUE THREAD

**Issue by Robert-Mar** [developer0hye/Simple-CenterNet#31]
![image](https://user-images.githubusercontent.com/52849989/131649331-d17a6552-5186-4258-aebe-3ce5dce4a566.png)

Thanks for your sharing, your code style is more easy to understand than the  official code. However, I am still confused about the process of loss computing. As the figure show, the code comes form `compute_loss()` function of models.centernet.py file. When debugging your code, I consider that the loss is repeated twice to solve for the mean, because the variable `batch_num_positive_samples` are the sum of all positive sample of each batch. Is this `/batch_size` operation redundant? And this operation may lead to lower loss value when training. I don't know if my understand is correct, hoping for your reply.

**Comment by developer0hye** [comment]
First, I wanted loss per image to be normalized by the number of positive samples to reduce the effect of images that have a lot of bounding boxes. Second, I wanted loss per batch to be normalized by the batch size to stablize scale of loss. Each normalize term has the diffrent goal.
