### ISSUE TITLE
NaN problem

### ISSUE THREAD

**Issue by ushio20** [developer0hye/Simple-CenterNet#32]
When I try to train with model resnet101 I find it occur NaN loss,do you encounter this problem?please tell me how to solve it,My batchsize with this model is 16.

**Comment by ushio20** [comment]
Resnet152 is also,but 18,32,50 is OK.

**Comment by developer0hye** [comment]
@ushio20 
I will check it. It will takes about 2 days.

**Comment by developer0hye** [comment]
@ushio20 
Can you test with fix-nan-loss branch?

**Comment by ushio20** [comment]
no,it will report error.I don't know how to fix NAN problem

**Comment by developer0hye** [comment]
@ushio20 

Run the below command and try training model with resnet101
```
git clone https://github.com/developer0hye/Simple-CenterNet/
cd Simple-CenterNet
git checkout -t origin/fix-nan-loss
python train.py
```

**Comment by ushio20** [comment]
OK,I will try it,thank you

**Comment by developer0hye** [comment]
@ushio20 

Did you try training your model with updated version?

**Comment by ushio20** [comment]
> @ushio20
> 
> Did you try training your model with updated version?

Yes,I'm training,about one day to know result.

**Comment by developer0hye** [comment]
@ushio20 
Okay! I hope it to be worked without any issues!

**Comment by developer0hye** [comment]
@ushio20 Do you have any issues?

**Comment by ushio20** [comment]
> @ushio20 Do you have any issue?

ok,it works!

**Comment by developer0hye** [comment]
@ushio20 
Great! Feel free to inform me about any issues
